name: tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        grammar: [1]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Validate JSON schemas
        run: |
          #pip install jsonschema
          #python test/validate_schemas.py

      - name: Install test harness dependency
        run: pip install pytest

      - name: Setup LLVM
        uses: ZhongRuoyu/setup-llvm@v0
        with:
          llvm-version: 22

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
          # the first mirror that worked, hardcoded to reduce workflow time
          mirror: https://pkg.hexops.org/zig 

      - name: Build compiler
        run: zig build --release=fast -DllvmIncludeDir=$(llvm-config --includedir) -DllvmLibDir=$(llvm-config --libdir) -DllvmLibName=$(llvm-config --libs x86)

      - name: Run tests for grammar ${{ matrix.grammar }}
        run: python3 test/run_tests.py test --grammar ${{ matrix.grammar }} --no-build
